### ISSUE TITLE
WebUI - JWT token not sent search requests

### ISSUE THREAD

**Issue by SamirMaina-districtm** [verdaccio/ui#118]
**Describe the bug**
When using JWT tokens in the UI, searching always returns no results. Looking at the request made to `/-/verdaccio/search/`, the `Authorization` header is missing in the request.

If packages are protected by `$authenticated` in the config, this results in an authorization failure:
```
verdaccio_1  |  info <-- 192.168.0.0 requested 'GET /-/verdaccio/search/boo'
verdaccio_1  |  trace--- allow access for @boost/styles
verdaccio_1  |  trace--- [auth/allow_action]: user: undefined
verdaccio_1  |  trace--- [auth/allow_action]: hasPermission? false for user: undefined
verdaccio_1  |  trace--- forbidden access for @boost/styles. Error: authorization required to access package @boost/styles
```

Using:
- Verdaccio 4.2.1 via docker-compose

1. Start verdaccio with below config and add any packages
2. Login to web portal
3. Note requests use JWT token
3. Attempt to search
4. Note missing JWT token in the search request 
5. Note errors in verdaccio logs

**Expected behavior**
Search requests in the web UI should also include the JWT token if the user is logged in.

**Docker || Kubernetes (please complete the following information):**
- Docker verdaccio tag: verdaccio:4
- Docker Version 18.06.1-ce
- Docker Compose Version: 1.24.1, build 4667896b

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
Using defaults for `security` but enforcing `$authenticated` for all packages:
```
security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
```

**Environment information**
No changes to Dockerfile. For reference, here's `verdaccio --info` output:
```Environment Info:

  System:
    OS: Linux 4.14 Alpine Linux undefined
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
```
