### ISSUE TITLE
authorization required to access packag  4.2.2

### ISSUE THREAD

**Issue by zanjs** [verdaccio/ui#126]
```
 warn --- http address - http://localhost:4873/ - verdaccio/4.2.2
 http <-- 304, user: zan(192.168.0.196 via 127.0.0.1), req: 'GET /@zan/panda', bytes: 0/0
 http <-- 401, user: null(192.168.0.196 via 127.0.0.1), req: 'GET /@zan/panda/-/panda-0.0.142.tgz', error: authorization required to access package @zan/panda
```

config

```
packages:
  '@zan/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    # access: $all
    access: $authenticated
    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incomming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enought.
server:
  keepAliveTimeout: 160

middlewares:
  audit:
    enabled: true
```
