### ISSUE TITLE
In the built app not found fonts

### ISSUE THREAD

**Issue by prog83** [verdaccio/ui#128]
**Describe the bug**
in the built app not found fonts

**To Reproduce**
1. Clone repo
2. yarn install
3. yarn build
4. Replace folder `static` in `@verdaccio/ui-theme` or installing same as plugin (config `config.yaml` theme section)
5. http://localhost:4873/ 
6. DevTools (F12) -> Network

**Screenshots**
![изображение](https://user-images.githubusercontent.com/31012354/65508669-611beb80-ded9-11e9-90d1-b6a590cf6ed6.png)

![изображение](https://user-images.githubusercontent.com/31012354/65508796-b48e3980-ded9-11e9-93a5-98af00f2a722.png)

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

**Solution**
\tools\webpack.config.js  line 69
` - name: 'fonts/[name].[ext]',`
` + name: '/fonts/[name].[ext]',`

**Comment by ViceIce** [comment]
This is related to #108 , seeing this with verdaccio 4.2.2

**Comment by ViceIce** [comment]
Also forcing `@verdaccio/ui-theme` to `v0.3.0` does not solve the issue.

**Comment by ViceIce** [comment]
`~$ cat node_modules/@verdaccio/ui-theme/static/0.style.9777bf15428fe89a9b2c.css`
```css
/*!
 *
 *     Name: vendors
 *     Generated on: 1567336977669
 *     Package: @verdaccio/ui-theme
 *     Version: v0.3.0
 *     License: MIT
 *
 */@font-face{font-family:Roboto;font-style:normal;font-display:swap;font-weight:100;src:local("Roboto Thin "),local("Roboto-Thin"),url(/-/staticfonts/roboto-latin-100.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-100.woff) format("woff")}@font-face{font-family:Roboto;font-style:italic;font-display:swap;font-weight:100;src:local("Roboto Thin italic"),local("Roboto-Thinitalic"),url(/-/staticfonts/roboto-latin-100italic.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-100italic.woff) format("woff")}@font-face{font-family:Roboto;font-style:normal;font-display:swap;font-weight:300;src:local("Roboto Light "),local("Roboto-Light"),url(/-/staticfonts/roboto-latin-300.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-300.woff) format("woff")}@font-face{font-family:Roboto;font-style:italic;font-display:swap;font-weight:300;src:local("Roboto Light italic"),local("Roboto-Lightitalic"),url(/-/staticfonts/roboto-latin-300italic.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-300italic.woff) format("woff")}@font-face{font-family:Roboto;font-style:normal;font-display:swap;font-weight:400;src:local("Roboto Regular "),local("Roboto-Regular"),url(/-/staticfonts/roboto-latin-400.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-400.woff) format("woff")}@font-face{font-family:Roboto;font-style:italic;font-display:swap;font-weight:400;src:local("Roboto Regular italic"),local("Roboto-Regularitalic"),url(/-/staticfonts/roboto-latin-400italic.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-400italic.woff) format("woff")}@font-face{font-family:Roboto;font-style:normal;font-display:swap;font-weight:500;src:local("Roboto Medium "),local("Roboto-Medium"),url(/-/staticfonts/roboto-latin-500.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-500.woff) format("woff")}@font-face{font-family:Roboto;font-style:italic;font-display:swap;font-weight:500;src:local("Roboto Medium italic"),local("Roboto-Mediumitalic"),url(/-/staticfonts/roboto-latin-500italic.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-500italic.woff) format("woff")}@font-face{font-family:Roboto;font-style:normal;font-display:swap;font-weight:700;src:local("Roboto Bold "),local("Roboto-Bold"),url(/-/staticfonts/roboto-latin-700.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-700.woff) format("woff")}@font-face{font-family:Roboto;font-style:italic;font-display:swap;font-weight:700;src:local("Roboto Bold italic"),local("Roboto-Bolditalic"),url(/-/staticfonts/roboto-latin-700italic.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-700italic.woff) format("woff")}@font-face{font-family:Roboto;font-style:normal;font-display:swap;font-weight:900;src:local("Roboto Black "),local("Roboto-Black"),url(/-/staticfonts/roboto-latin-900.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-900.woff) format("woff")}@font-face{font-family:Roboto;font-style:italic;font-display:swap;font-weight:900;src:local("Roboto Black italic"),local("Roboto-Blackitalic"),url(/-/staticfonts/roboto-latin-900italic.woff2) format("woff2"),url(/-/staticfonts/roboto-latin-900italic.woff) format("woff")}


/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}main{display:block}h1{font-size:2em;margin:.67em 0}hr{box-sizing:content-box;height:0;overflow:visible}pre{font-family:monospace,monospace;font-size:1em}a{background-color:transparent}abbr[title]{border-bottom:none;text-decoration:underline;text-decoration:underline dotted}b,strong{font-weight:bolder}code,kbd,samp{font-family:monospace,monospace;font-size:1em}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}sub{bottom:-.25em}sup{top:-.5em}img{border-style:none}button,input,optgroup,select,textarea{font-family:inherit;font-size:100%;line-height:1.15;margin:0}button,input{overflow:visible}button,select{text-transform:none}[type=button],[type=reset],[type=submit],button{-webkit-appearance:button}[type=button]::-moz-focus-inner,[type=reset]::-moz-focus-inner,[type=submit]::-moz-focus-inner,button::-moz-focus-inner{border-style:none;padding:0}[type=button]:-moz-focusring,[type=reset]:-moz-focusring,[type=submit]:-moz-focusring,button:-moz-focusring{outline:1px dotted ButtonText}fieldset{padding:.35em .75em .625em}legend{box-sizing:border-box;color:inherit;display:table;max-width:100%;padding:0;white-space:normal}progress{vertical-align:baseline}textarea{overflow:auto}[type=checkbox],[type=radio]{box-sizing:border-box;padding:0}[type=number]::-webkit-inner-spin-button,[type=number]::-webkit-outer-spin-button{height:auto}[type=search]{-webkit-appearance:textfield;outline-offset:-2px}[type=search]::-webkit-search-decoration{-webkit-appearance:none}::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}details{display:block}summary{display:list-item}[hidden],template{display:none}
```
