### ISSUE TITLE
Download button is not displayed if the tarball dist URI has localhost as domain

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/ui#76]
**Describe the bug**

The download button is hidden if I run `verdaccio` as `localhost`.

The reason is the `validator` library and the current setup, validate 

```
"http://localhost:8080/@verdaccio%2fui-theme/-/ui-theme-0.2.0.tgz"
```
as false.
```
export function isURL(url): boolean {
  return isURLValidator(url || '', {
    protocols: ['http', 'https', 'git+https'],
    require_protocol: true,
  });
}
```

**To Reproduce**

1. Publish any package
2. Go to the detail page
3. The button is not being rendered

**Expected behavior**

In localhost environments, this should be valid.

**Screenshots**

![Screen Shot 2019-06-20 at 5 26 39 PM](https://user-images.githubusercontent.com/558752/59861166-9bc53380-9380-11e9-825c-1db2f1ecf376.png)

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
Packages protected
```
packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
```

**Additional context**
